from app.auth.schemas.request import (
    AssignPermissionRequest,
    AssignRoleRequest,
    ChangePasswordRequest,
    CreatePermissionRequest,
    CreateRoleRequest,
    ForgotPasswordRequest,
    LoginRequest,
    RefreshRequest,
    RegisterRequest,
    ResetPasswordRequest,
    UpdatePermissionRequest,
    UpdateProfileRequest,
    UpdateRoleRequest,
)
from app.auth.schemas.response import (
    AccessTokenResponse,
    AuthTokens,
    LoginResponse,
    PasswordResetTokenResponse,
    PermissionResponse,
    ProfileResponse,
    RegisterResponse,
    RolePermissionResponse,
    RoleResponse,
    RoleWithPermissionsResponse,
    UserResponse,
    UserWithProfileResponse,
)

__all__ = [
    # Request
    "RegisterRequest",
    "LoginRequest",
    "RefreshRequest",
    "ForgotPasswordRequest",
    "ResetPasswordRequest",
    "ChangePasswordRequest",
    "UpdateProfileRequest",
    "CreateRoleRequest",
    "UpdateRoleRequest",
    "AssignRoleRequest",
    "CreatePermissionRequest",
    "UpdatePermissionRequest",
    "AssignPermissionRequest",
    # Response
    "PermissionResponse",
    "RoleResponse",
    "RoleWithPermissionsResponse",
    "RolePermissionResponse",
    "ProfileResponse",
    "UserResponse",
    "UserWithProfileResponse",
    "AuthTokens",
    "AccessTokenResponse",
    "RegisterResponse",
    "LoginResponse",
    "PasswordResetTokenResponse",
]
