<#
.SYNOPSIS
  Windows equivalent of the Makefile — run dev/prod Docker tasks.

.EXAMPLE
  .\dev.ps1 dev-build
  .\dev.ps1 migrate
  .\dev.ps1 help
#>

param(
    [string]$Task = "help",
    [string]$Msg  = "migration"
)

$DEV  = "docker compose -f docker-compose.dev.yml"
$PROD = "docker compose"

switch ($Task) {

    # ── Development ───────────────────────────────────────────────────────────

    "dev" {
        Invoke-Expression "$DEV up -d"
    }
    "dev-build" {
        Invoke-Expression "$DEV up --build -d"
    }
    "dev-down" {
        Invoke-Expression "$DEV down"
    }

    # ── Production ────────────────────────────────────────────────────────────

    "prod" {
        Invoke-Expression "$PROD up -d"
    }
    "prod-build" {
        Invoke-Expression "$PROD up --build -d"
    }
    "prod-down" {
        Invoke-Expression "$PROD down"
    }

    # ── Logs ──────────────────────────────────────────────────────────────────

    "logs" {
        Invoke-Expression "$DEV logs -f app"
    }
    "logs-worker" {
        Invoke-Expression "$DEV logs -f worker"
    }

    # ── Database ──────────────────────────────────────────────────────────────

    "migrate" {
        Invoke-Expression "$DEV exec app sh -c 'cd /app/backend && .venv/bin/alembic upgrade head'"
    }
    "migrate-new" {
        Invoke-Expression "$DEV exec app sh -c 'cd /app/backend && .venv/bin/alembic revision --autogenerate -m ""$Msg""'"
    }
    "seed" {
        Invoke-Expression "$DEV exec app sh -c 'cd /app/backend && .venv/bin/python scripts/seed.py'"
    }

    # ── Shell ─────────────────────────────────────────────────────────────────

    "shell" {
        Invoke-Expression "$DEV exec app bash"
    }

    # ── Help ──────────────────────────────────────────────────────────────────

    default {
        Write-Host ""
        Write-Host "  Usage: .\dev.ps1 <task> [-Msg '<description>']"
        Write-Host ""
        Write-Host "  dev           Start dev stack (hot-reload)"
        Write-Host "  dev-build     Rebuild dev image and start"
        Write-Host "  dev-down      Stop dev stack"
        Write-Host ""
        Write-Host "  prod          Start production stack"
        Write-Host "  prod-build    Rebuild prod image and start"
        Write-Host "  prod-down     Stop production stack"
        Write-Host ""
        Write-Host "  logs          Follow app logs (dev)"
        Write-Host "  logs-worker   Follow worker logs (dev)"
        Write-Host ""
        Write-Host "  migrate       Apply all pending migrations (dev)"
        Write-Host "  migrate-new   Generate a new autogenerated migration (use -Msg 'description')"
        Write-Host "  seed          Run database seeder (dev)"
        Write-Host "  shell         Open bash shell in app container (dev)"
        Write-Host ""
    }
}
