.PHONY: dev dev-build dev-down \
        prod prod-build prod-down \
        cqrs cqrs-build cqrs-down \
        logs logs-worker \
        logs-gateway logs-chat-cmd logs-chat-qry logs-plot-cmd logs-plot-qry \
        shell shell-gateway \
        migrate migrate-new seed \
        help

MSG ?= migration

# ── Development (Monolith) ─────────────────────────────────────────────────────
# Services: FastAPI (uvicorn --reload) + Next.js (bun dev) + Nginx + Celery worker
#           + PostgreSQL 16 + Redis 7 + pgAdmin + Redis Commander
# Source is volume-mounted — file changes are picked up without rebuilding.

dev:
	docker compose -f docker-compose.dev.yml up -d

dev-build:
	docker compose -f docker-compose.dev.yml up --build -d

dev-down:
	docker compose -f docker-compose.dev.yml down

# ── Production (Monolith) ──────────────────────────────────────────────────────
# Services: Gunicorn (uvicorn workers) + Next.js standalone + Nginx + Celery worker
#           + PostgreSQL 16 + Redis 7
# Multi-stage build: frontend compiled to standalone, Python venv pre-built.

prod:
	docker compose up -d

prod-build:
	docker compose up --build -d

prod-down:
	docker compose down

# ── CQRS Microservices ─────────────────────────────────────────────────────────
# Services: api-gateway + chat-command + chat-query + plot-command + plot-query
#           + Zookeeper + Kafka (1 broker) + kafka-init + Kafka UI + PostgreSQL
# kafka-init runs once to create the 4 topics, then exits.
# CQRS services auto-create DB tables (SQLAlchemy create_all) on startup.

cqrs:
	docker compose -f docker-compose.cqrs.yml up -d

cqrs-build:
	docker compose -f docker-compose.cqrs.yml up --build -d

cqrs-down:
	docker compose -f docker-compose.cqrs.yml down

# ── Logs ───────────────────────────────────────────────────────────────────────

logs:
	docker compose -f docker-compose.dev.yml logs -f app

logs-worker:
	docker compose -f docker-compose.dev.yml logs -f worker

logs-gateway:
	docker compose -f docker-compose.cqrs.yml logs -f api-gateway

logs-chat-cmd:
	docker compose -f docker-compose.cqrs.yml logs -f chat-command

logs-chat-qry:
	docker compose -f docker-compose.cqrs.yml logs -f chat-query

logs-plot-cmd:
	docker compose -f docker-compose.cqrs.yml logs -f plot-command

logs-plot-qry:
	docker compose -f docker-compose.cqrs.yml logs -f plot-query

# ── Database (monolith dev) ────────────────────────────────────────────────────

migrate:
	docker compose -f docker-compose.dev.yml exec app \
	  sh -c "cd /app/backend && .venv/bin/alembic upgrade head"

migrate-new:
	docker compose -f docker-compose.dev.yml exec app \
	  sh -c "cd /app/backend && .venv/bin/alembic revision --autogenerate -m '$(MSG)'"

seed:
	docker compose -f docker-compose.dev.yml exec app \
	  sh -c "cd /app/backend && .venv/bin/python scripts/seed.py"

# ── Shell ──────────────────────────────────────────────────────────────────────

shell:
	docker compose -f docker-compose.dev.yml exec app bash

shell-gateway:
	docker compose -f docker-compose.cqrs.yml exec api-gateway bash

# ── Help ───────────────────────────────────────────────────────────────────────

help:
	@echo ""
	@echo "  Monolith — Development  (docker-compose.dev.yml)"
	@echo "  ──────────────────────────────────────────────────────────────────"
	@echo "  make dev              Start monolith dev stack (hot-reload)"
	@echo "  make dev-build        Rebuild image and start dev stack"
	@echo "  make dev-down         Stop dev stack"
	@echo ""
	@echo "  Monolith — Production  (docker-compose.yml)"
	@echo "  ──────────────────────────────────────────────────────────────────"
	@echo "  make prod             Start monolith production stack"
	@echo "  make prod-build       Rebuild image and start production stack"
	@echo "  make prod-down        Stop production stack"
	@echo ""
	@echo "  CQRS Microservices  (docker-compose.cqrs.yml)"
	@echo "  ──────────────────────────────────────────────────────────────────"
	@echo "  make cqrs             Start CQRS stack"
	@echo "  make cqrs-build       Rebuild all 5 service images and start"
	@echo "  make cqrs-down        Stop CQRS stack"
	@echo ""
	@echo "  Logs"
	@echo "  ──────────────────────────────────────────────────────────────────"
	@echo "  make logs             Follow app logs           (monolith dev)"
	@echo "  make logs-worker      Follow Celery worker logs (monolith dev)"
	@echo "  make logs-gateway     Follow api-gateway logs   (CQRS)"
	@echo "  make logs-chat-cmd    Follow chat-command logs  (CQRS)"
	@echo "  make logs-chat-qry    Follow chat-query logs    (CQRS)"
	@echo "  make logs-plot-cmd    Follow plot-command logs  (CQRS)"
	@echo "  make logs-plot-qry    Follow plot-query logs    (CQRS)"
	@echo ""
	@echo "  Database  (monolith dev)"
	@echo "  ──────────────────────────────────────────────────────────────────"
	@echo "  make migrate               Apply all pending Alembic migrations"
	@echo "  make migrate-new MSG='...' Generate a new autogenerated migration"
	@echo "  make seed                  Run the database seeder"
	@echo ""
	@echo "  Shell"
	@echo "  ──────────────────────────────────────────────────────────────────"
	@echo "  make shell            Open bash in app container (monolith dev)"
	@echo "  make shell-gateway    Open bash in api-gateway   (CQRS)"
	@echo ""
