.PHONY: dev dev-build dev-down \
        prod prod-build prod-down \
        logs logs-worker \
        shell migrate migrate-new seed \
        help

MSG ?= migration

# ── Development ───────────────────────────────────────────────────────────────

dev:
	docker compose -f docker-compose.dev.yml up -d

dev-build:
	docker compose -f docker-compose.dev.yml up --build -d

dev-down:
	docker compose -f docker-compose.dev.yml down

# ── Production ────────────────────────────────────────────────────────────────

prod:
	docker compose up -d

prod-build:
	docker compose up --build -d

prod-down:
	docker compose down

# ── Logs ──────────────────────────────────────────────────────────────────────

logs:
	docker compose -f docker-compose.dev.yml logs -f app

logs-worker:
	docker compose -f docker-compose.dev.yml logs -f worker

# ── Database ──────────────────────────────────────────────────────────────────

migrate:
	docker compose -f docker-compose.dev.yml exec app \
	  sh -c "cd /app/backend && .venv/bin/alembic upgrade head"

migrate-new:
	docker compose -f docker-compose.dev.yml exec app \
	  sh -c "cd /app/backend && .venv/bin/alembic revision --autogenerate -m '$(MSG)'"

seed:
	docker compose -f docker-compose.dev.yml exec app \
	  sh -c "cd /app/backend && .venv/bin/python scripts/seed.py"

# ── Shell ─────────────────────────────────────────────────────────────────────

shell:
	docker compose -f docker-compose.dev.yml exec app bash

# ── Help ──────────────────────────────────────────────────────────────────────

help:
	@echo ""
	@echo "  make dev          Start dev stack (hot-reload)"
	@echo "  make dev-build    Rebuild dev image and start"
	@echo "  make dev-down     Stop dev stack"
	@echo "  make prod         Start production stack"
	@echo "  make prod-build   Rebuild prod image and start"
	@echo "  make prod-down    Stop production stack"
	@echo "  make logs         Follow app logs (dev)"
	@echo "  make logs-worker  Follow worker logs (dev)"
	@echo "  make migrate               Apply all pending migrations (dev)"
	@echo "  make migrate-new MSG='...' Generate a new autogenerated migration (dev)"
	@echo "  make seed                  Run database seeder (dev)"
	@echo "  make shell                 Open bash shell in app container (dev)"
	@echo ""
