"""rewrite auth schema v2

Revision ID: 8fc26df91f7c
Revises: 1b7e3a7f6412
Create Date: 2026-04-25 17:51:14.739774

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8fc26df91f7c'
down_revision: Union[str, Sequence[str], None] = '1b7e3a7f6412'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_index('idx_permissions_name', 'permissions', ['name'], unique=False)
    op.create_table('roles',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_roles_short_name', 'roles', ['short_name'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permission_role_id_permission_id')
    )
    op.create_index('idx_role_permission_permission_id', 'role_permissions', ['permission_id'], unique=False)
    op.create_index('idx_role_permission_role_id', 'role_permissions', ['role_id'], unique=False)
    op.create_index(op.f('ix_role_permissions_permission_id'), 'role_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_role_permissions_role_id'), 'role_permissions', ['role_id'], unique=False)
    op.create_table('sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('geo_location', sa.String(length=255), nullable=True),
    sa.Column('device_type', sa.String(length=20), nullable=True),
    sa.Column('access_token_hash', sa.String(length=255), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), server_default='false', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_session_revoked', 'sessions', ['revoked_at'], unique=False)
    op.create_index('idx_session_user_expires', 'sessions', ['user_id', 'expires_at'], unique=False)
    op.create_index(op.f('ix_sessions_access_token_hash'), 'sessions', ['access_token_hash'], unique=False)
    op.create_index(op.f('ix_sessions_device_type'), 'sessions', ['device_type'], unique=False)
    op.create_index(op.f('ix_sessions_expires_at'), 'sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_sessions_refresh_token_hash'), 'sessions', ['refresh_token_hash'], unique=True)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_index('uq_active_session_per_user', 'sessions', ['user_id'], unique=True, postgresql_where=sa.text('revoked_at IS NULL'))
    op.create_index('idx_password_reset_tokens_user_id', 'password_reset_tokens', ['user_id'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.add_column('profiles', sa.Column('fname', sa.String(length=255), nullable=True))
    op.add_column('profiles', sa.Column('lname', sa.String(length=255), nullable=True))
    op.add_column('profiles', sa.Column('company', sa.String(length=255), nullable=True))
    op.add_column('profiles', sa.Column('department', sa.String(length=255), nullable=True))
    op.add_column('profiles', sa.Column('designation', sa.String(length=255), nullable=True))
    op.add_column('profiles', sa.Column('company_role', sa.String(length=255), nullable=True))
    op.add_column('profiles', sa.Column('location', sa.String(length=255), nullable=True))
    op.add_column('profiles', sa.Column('photo', sa.Text(), nullable=True))
    op.alter_column('profiles', 'phone',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.create_index('idx_profiles_company_department', 'profiles', ['company', 'department'], unique=False)
    op.create_index('idx_profiles_user_id', 'profiles', ['user_id'], unique=False)
    op.drop_column('profiles', 'avatar_url')
    op.drop_column('profiles', 'first_name')
    op.drop_column('profiles', 'last_name')
    op.add_column('users', sa.Column('role_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_users_role_id'), 'users', ['role_id'], unique=False)
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'], ondelete='SET NULL')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', postgresql.ENUM('SUPERADMIN', 'ADMIN', 'MEMBER', name='role'), server_default=sa.text("'MEMBER'::role"), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_role_id'), table_name='users')
    op.drop_column('users', 'role_id')
    op.add_column('profiles', sa.Column('last_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('first_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('avatar_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_index('idx_profiles_user_id', table_name='profiles')
    op.drop_index('idx_profiles_company_department', table_name='profiles')
    op.alter_column('profiles', 'phone',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.drop_column('profiles', 'photo')
    op.drop_column('profiles', 'location')
    op.drop_column('profiles', 'company_role')
    op.drop_column('profiles', 'designation')
    op.drop_column('profiles', 'department')
    op.drop_column('profiles', 'company')
    op.drop_column('profiles', 'lname')
    op.drop_column('profiles', 'fname')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index('idx_password_reset_tokens_user_id', table_name='password_reset_tokens')
    op.drop_index('uq_active_session_per_user', table_name='sessions', postgresql_where=sa.text('revoked_at IS NULL'))
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_refresh_token_hash'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_expires_at'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_device_type'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_access_token_hash'), table_name='sessions')
    op.drop_index('idx_session_user_expires', table_name='sessions')
    op.drop_index('idx_session_revoked', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_role_permissions_role_id'), table_name='role_permissions')
    op.drop_index(op.f('ix_role_permissions_permission_id'), table_name='role_permissions')
    op.drop_index('idx_role_permission_role_id', table_name='role_permissions')
    op.drop_index('idx_role_permission_permission_id', table_name='role_permissions')
    op.drop_table('role_permissions')
    op.drop_index('idx_roles_short_name', table_name='roles')
    op.drop_table('roles')
    op.drop_index('idx_permissions_name', table_name='permissions')
    op.drop_table('permissions')
    # ### end Alembic commands ###
