"""add sheets table

Revision ID: 18a4e8037c45
Revises: a1b2c3d4e5f6
Create Date: 2026-06-06 18:38:41.331204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18a4e8037c45'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_azure_id'), 'users', type_='unique')
    op.drop_constraint(op.f('uq_users_google_id'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_azure_id'), table_name='users')
    op.create_index(op.f('ix_users_azure_id'), 'users', ['azure_id'], unique=True)
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=False)
    op.drop_index(op.f('ix_users_azure_id'), table_name='users')
    op.create_index(op.f('ix_users_azure_id'), 'users', ['azure_id'], unique=False)
    op.create_unique_constraint(op.f('uq_users_google_id'), 'users', ['google_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_users_azure_id'), 'users', ['azure_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
